### PR TITLE
Change link and credit to CSS draft

### PR DESCRIPTION
**Pull request by jonathanKingston**

### CODE REVIEW

**Comment by zcorpan** [comment]
You're also listed as editor?

**Comment by gregwhitworth** [comment]
Yes because he is the one actually put it in spec form. I'm kind of confused however on why you linked to another spec. I thought the goal was to lift Aspect Ratio into its own spec and have it stand on its own. Then we can bring the sizing logical props as their own addition.

**Comment by jonathanKingston** [comment]
I did this pull the other week... Still not done the other yet. Sorry I
should have it done by today 😃.

**Comment by gregwhitworth** [comment]
@jonathanKingston Sounds good - how is this coming along? I'd like to be able to review it, send it around to some other people to review as well.

**Comment by gregwhitworth** [comment]
Ok, I want to have someone review this - so I dropped in the base stuff. I'm going to do some refining from here. I'm closing this PR.

**Pull request closed without merging**
